spring.application.name=tomcat-demo

## 服务器一般配置项

# web服务绑定的网络接口的IP地址，支持配置多个，以逗号分隔开
# 理解：之前没有理解，可以这样理解，就是服务监听的地址，例如配置了：192.168.1.100，那么服务会监听该地址的网络请求
# 默认情况下，springboot 应用程序会绑定到所有可用的网络接口（即监听所有IP地址），这意味着你的应用程序将对所有网络接口上的客户端开放。
# 该配置项应用场景：
# 1.限制访问（安全性）：如果你希望应用程序只对特定的网络或IP地址开放，你可以设置 server.address 为特定的IP地址。
# 2.多网卡环境：在多网络接口的服务器上，你可能希望应用程序只绑定到一个特定的网络接口。
# 3.避免冲突：如果你的应用程序需要在同一台机器上运行多个实例，并且这些实例需要监听不同的端口，你可以为每个实例设置不同的 server.address。
#server.address
#server.port=8080
#server.shutdown=immediate
#server.compression.enabled=false
#server.compression.excluded-user-agents
#server.compression.mime-types=[text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, application/xml]
#server.compression.min-response-size
#server.error.include-binding-errors
#server.error.include-exception
#server.error.include-message
#server.error.include-stacktrace
# 配置当前项目出错时跳转去的页面，默认值是 /error
#server.error.path=/error
#server.error.whitelabel.enabled
#server.forward-headers-strategy
# http请求头的最大大小，默认为 8192 字节（8KB）
server.max-http-header-size=8KB
#server.http2.enabled=false
#server.server-header
#server.servlet.application-display-name=application
# ServletContext 初始化参数，是个 map 结构
#server.servlet.context-parameters.*
server.servlet.context-parameters.key1=value1
server.servlet.context-parameters.key2=value2
# 配置项目的 context-path，默认值是 /
# 如果配置了该值，则项目中的所有访问路径中要加上配置的路径。例如配置的是 /demo，访问路径则为：http://localhost:8080/demo/hello
#server.servlet.context-path=/
#server.servlet.encoding.charset
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force
#server.servlet.encoding.force-request
#server.servlet.encoding.force-response
#server.servlet.encoding.mapping.*
#server.servlet.jsp.class-name
#server.servlet.jsp.init-parameters.*
#server.servlet.jsp.registered
#server.servlet.register-default-servlet=false
#server.servlet.session.cookie.comment
#server.servlet.session.cookie.domain
#server.servlet.session.cookie.http-only
#server.servlet.session.cookie.max-age
#server.servlet.session.cookie.name
#server.servlet.session.cookie.path
#server.servlet.session.cookie.same-site
#server.servlet.session.cookie.secure
#server.servlet.session.persistent
#server.servlet.session.store-dir
# session 超时时间，默认值是 30m。
# tomcat 中配置 session 过期时间是以分钟为单位。如果不写单位则默认单位是秒，如果设置为秒，则会自动转换为不超过所配置秒数的最大分钟数。
# 比如配置了 119 秒，那么实际 session 过期时间是 1 分钟
#server.servlet.session.timeout=30m
#server.servlet.session.tracking-modes

#server.ssl.certificate
#server.ssl.certificate-private-key
#server.ssl.ciphers
#server.ssl.client-auth
#server.ssl.enabled
#server.ssl.enabled-protocols
# 密钥别名
#server.ssl.key-alias
#server.ssl.key-password
# 密钥存储路径，通常是个 jks 文件，
#server.ssl.key-store
# 创建证书过程中输入的密码
#server.ssl.key-store-password
#server.ssl.key-store-provider
#server.ssl.key-store-type
#server.ssl.protocol
#server.ssl.trust-certificate
#server.ssl.trust-certificate-private-key
#server.ssl.trust-store
#server.ssl.trust-store-password
#server.ssl.trust-store-provider
#server.ssl.trust-store-type


# 启动tomcat中的访问日志
#server.tomcat.accesslog.enabled
# tomcat中访问日志文件的一些参数，如附加到日志文件的目录名，前缀，后缀和日期格式
#server.tomcat.accesslog.directory=logs # 如果配置的是相对路径，默认会在tomcat的运行目录下生成该目录
#server.tomcat.accesslog.file-date-format
#server.tomcat.accesslog.prefix=access_log
#server.tomcat.accesslog.suffix=.log

#server.tomcat.accesslog.buffered=true
#server.tomcat.accesslog.check-exists=false
#server.tomcat.accesslog.condition-if=
#server.tomcat.accesslog.condition-unless

# 访问日志编码格式，默认值是系统的默认字符集
#server.tomcat.accesslog.encoding
#server.tomcat.accesslog.ipv6-canonical
#server.tomcat.accesslog.locale
#server.tomcat.accesslog.max-days
#server.tomcat.accesslog.pattern

#server.tomcat.accesslog.rename-on-rotate
#server.tomcat.accesslog.request-attributes-enabled
#server.tomcat.accesslog.rotate

#server.tomcat.additional-tld-skip-patterns
#server.tomcat.background-processor-delay
# tomcat 运行目录，里面包含了配置文件，部署的web项目，运行时日志等等。若不配置，则默认使用系统的临时目录。
# 例如windows系统就在：C:\Users\xxx\AppData\Local\Temp\tomcat.8080.4654207823524165758，tomcat.8080.4654207823524165758是生成的，每次启动生成的是不一样的
#server.tomcat.basedir



# tomcat 服务器最大连接数，默认值是8192
server.tomcat.max-connections=8192
# tomcat 服务器等待队列的长度，默认值是100，即如果此时服务器接收的连接数已经超过了最大连接数，新来的连接进入等待队列中，
# 该属性值就是声明等待队列的长度，如果超过等待队列长度，连接将会被丢弃
server.tomcat.accept-count=100
# tomcat 线程池最大线程数，默认值是200
server.tomcat.threads.max=200
# tomcat 线程池最小线程数，默认值是10
server.tomcat.threads.min-spare=10

# 最大并发量，这里有不同的理解
# 1.如果在乎tomcat运行能够同时处理的任务数量，那最大并发量可能理解成最大工作线程数（max-threads）---不包含队列里的数量（acceptCount）
# 2.如果在乎tomcat运行能够接纳的最大最多的任务数量，那最大并发量可以理解成最大连接数（max-connections）+ 队列长度的数量（accept-count） --- 包含队列里的数量（acceptCount）
# 这里 tomcat 是第二点，只关注能够接纳的最大最多的任务数量，
# 例如最大连接数是8192，等待队列是100，线程池最大线程数是200，那么tomcat最多只能接收8292个连接，即最大连接数（max-connections）+ 队列长度的数量（accept-count）
# 也就是正在线程池中处理的连接也是计算最大连接数内的

# 连接超时时间，socket 调用 read() 方法等待读取时间，如果超出该时间，主动断开连接
#server.tomcat.connection-timeout
#server.tomcat.keep-alive-timeout
# tomcat支持http请求正文的最大值，默认值为 2MB，
#server.tomcat.max-swallow-size=2MB
# tomcat支持http的post请求表单的最大值，默认值为 2MB，-1 表示不限制大小
#server.tomcat.max-http-form-post-size=2MB
#server.tomcat.max-keep-alive-requests=100

#server.tomcat.mbeanregistry.enabled=false
#server.tomcat.processor-cache=200
#server.tomcat.redirect-context-root=true
#server.tomcat.relaxed-path-chars
#server.tomcat.relaxed-query-chars
#server.tomcat.remoteip.host-header=X-Forwarded-Host
#server.tomcat.remoteip.internal-proxies=10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3}|169\\.254\\.\\d{1,3}\\.\\d{1,3}|127\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|100\\.6[4-9]{1}\\.\\d{1,3}\\.\\d{1,3}|100\\.[7-9]{1}\\d{1}\\.\\d{1,3}\\.\\d{1,3}|100\\.1[0-1]{1}\\d{1}\\.\\d{1,3}\\.\\d{1,3}|100\\.12[0-7]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.1[6-9]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.2[0-9]{1}\\.\\d{1,3}\\.\\d{1,3}|172\\.3[0-1]{1}\\.\\d{1,3}\\.\\d{1,3}|0:0:0:0:0:0:0:1|::1
#server.tomcat.remoteip.port-header
#server.tomcat.remoteip.protocol-header
#server.tomcat.remoteip.protocol-header-https-value
#server.tomcat.remoteip.remote-ip-header
#server.tomcat.resource.allow-caching
#server.tomcat.resource.cache-ttl

# tomcat 请求编码，默认值是 UTF-8，用于解码 URI 的字符编码
server.tomcat.uri-encoding=UTF-8
server.tomcat.use-relative-redirects=false